### ISSUE TITLE
Add ability to get authentication path to previous checkpoint

### ISSUE THREAD

**Issue by str4d** [zcash/incrementalmerkletree#22]
In `zcashd` we want to be able to fetch the authentication path from a wallet note to an anchor that is not necessarily the most recent tree root. In `incrementalmerkletree` terms, that means we need to alter `Tree::authentication_path` to take a `checkpoint_offset: usize` parameter, where `0` means "no offset, use the latest tree state", and non-zero values mean "ignore the most recent `checkpoint_offset` checkpoint intervals" (i.e. give the equivalent path that we'd get if we called `Tree::rewind` `checkpoint_offset` times and then called `Tree::authentication_path`.

**Comment by nuttycom** [comment]
Fixed by #38
